# Generated by Django 4.2.1 on 2023-06-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='translat',
            new_name='translate',
        ),
    ]
